// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Meters;

public enum MeterCounterCode
{
    TOTAL,
    BW,
    COLOR,
    SCAN,
}
