// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Auditing;

public enum AuditAction
{
    INSERT,
    UPDATE,
    DELETE,
    STATUS_CHANGE,
}
