// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Breakdowns;

public enum BreakdownReportedByType
{
    PORTAL_CONTACT,
    DATA_ENTRY_OPERATOR,
    TECHNICIAN,
    DEALER,
    SALESMAN,
}
