// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Breakdowns;

public enum BreakdownStatus
{
    PROCESSING,
    APPROVED,
    ASSIGNED,
    TRAVELLING,
    STARTED,
    COMPLETED,
    RECALL,
    CANCELLED,
}
