// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Installations;

public enum InstallationVerificationStatus
{
    PENDING_VERIFICATION,
    VERIFIED,
    REJECTED,
}
