// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Installations;

public enum InstallationJobStatus
{
    ASSIGNED,
    IN_PROGRESS,
    SUBMITTED,
    VERIFIED,
    COMPLETED,
    REJECTED,
    CANCELLED,
}
