// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Services;

public enum ServiceScheduleStatus
{
    SCHEDULED,
    DUE,
    STARTED,
    COMPLETED,
    RECALLED,
    CANCELLED,
}
