// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Agreements;

public enum AgreementStatus
{
    ACTIVE,
    EXPIRED,
    TERMINATED,
    CANCELLED,
}
