// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Machines;

public enum MachineAssignmentType
{
    OUTRIGHT_SALE,
    RENTAL,
}
