// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Notifications;

public enum NotificationDeliveryStatus
{
    PENDING,
    SENT,
    FAILED,
    READ,
}
