// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Notifications;

public enum NotificationRecipientType
{
    INTERNAL_USER,
    PORTAL_ACCOUNT,
}
