// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Notifications;

public enum NotificationChannel
{
    EMAIL,
    IN_APP,
    PUSH,
}
