// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Notifications;

public enum NotificationEventCode
{
    INSTALLATION_COMPLETED,
    PORTAL_CREDENTIALS_ISSUED,
    BREAKDOWN_APPROVED,
    TECHNICIAN_ASSIGNED,
    BREAKDOWN_COMPLETED,
    SERVICE_COMPLETED,
    ESTIMATE_SENT,
    ESTIMATE_ACCEPTED,
    UPCOMING_SERVICE,
}
