// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Estimates;

public enum EstimateAcceptedByType
{
    PORTAL_CONTACT,
    OPERATOR_ON_BEHALF,
}
