// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Estimates;

public enum EstimateStatus
{
    DRAFT,
    PENDING_PARTS,
    READY,
    SENT,
    ACCEPTED,
    REJECTED,
    EXPIRED,
    CANCELLED,
}
