// <auto-generated>
// Generated from the NewServvista DBML schema.
// </auto-generated>
#nullable enable

namespace NewServvista.Models.Enums.Estimates;

public enum EstimateLineStatus
{
    CATALOG,
    PENDING,
    RESOLVED,
}
