package com.gestetner.servvista.Service;

import com.gestetner.servvista.Dto.estimates.*;
import com.gestetner.servvista.Models.Enums.Estimates.*;
import com.gestetner.servvista.Models.entity.estimates.*;
import com.gestetner.servvista.Repositories.breakdowns.BreakdownRepository;
import com.gestetner.servvista.Repositories.customerportal.CustomerPortalAccountRepository;
import com.gestetner.servvista.Repositories.estimates.*;
import com.gestetner.servvista.Repositories.identity.*;
import com.gestetner.servvista.Repositories.machines.MachineRepository;
import com.gestetner.servvista.Repositories.parts.PartRepository;
import com.gestetner.servvista.Repositories.services.ServiceScheduleRepository;
import jakarta.persistence.EntityNotFoundException;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.List;

@Service @Transactional
public class EstimateService {
 private final EstimateRepository estimates; private final EstimateLineRepository lines; private final EstimateStatusHistoryRepository histories; private final EstimateAcceptanceRepository acceptances;
 private final MachineRepository machines; private final ServiceScheduleRepository schedules; private final BreakdownRepository breakdowns; private final TechnicianRepository technicians; private final UserRepository users; private final PartRepository parts; private final CustomerPortalAccountRepository portals;
 public EstimateService(EstimateRepository e,EstimateLineRepository l,EstimateStatusHistoryRepository h,EstimateAcceptanceRepository a,MachineRepository m,ServiceScheduleRepository s,BreakdownRepository b,TechnicianRepository t,UserRepository u,PartRepository p,CustomerPortalAccountRepository c){estimates=e;lines=l;histories=h;acceptances=a;machines=m;schedules=s;breakdowns=b;technicians=t;users=u;parts=p;portals=c;}

 public EstimateResponse create(EstimateRequest r){validate(r);EstimateStatus status=r.status()==null?EstimateStatus.DRAFT:r.status();LocalDateTime now=LocalDateTime.now();try{Estimate e=new Estimate();e.setEstimateNumber("ES"+String.format("%06d",estimates.findMaximumEstimateSequence()+1));apply(e,r,status,true,now);e=estimates.saveAndFlush(e);replaceLines(e.getEstimateId(),r.lines());addHistory(e.getEstimateId(),null,status,r.performedBy(),r.statusReason(),now);syncAcceptance(e.getEstimateId(),status,r.acceptance(),now);return response(find(e.getEstimateId()));}catch(DataIntegrityViolationException x){throw conflict("Estimate could not be created",x);}}
 @Transactional(readOnly=true) public List<EstimateResponse> getAll(){return estimates.findAllWithDetails().stream().map(this::response).toList();}
 @Transactional(readOnly=true) public EstimateResponse getById(Long id){return response(find(id));}
 public EstimateResponse update(Long id,EstimateRequest r){Estimate e=find(id);validate(r);EstimateStatus old=e.getStatus(),status=r.status()==null?old:r.status();LocalDateTime now=LocalDateTime.now();try{apply(e,r,status,false,now);estimates.saveAndFlush(e);replaceLines(id,r.lines());if(old!=status)addHistory(id,old,status,r.performedBy(),r.statusReason(),now);syncAcceptance(id,status,r.acceptance(),now);return response(find(id));}catch(DataIntegrityViolationException x){throw conflict("Estimate could not be updated",x);}}
 public void delete(Long id){Estimate e=find(id);try{acceptances.deleteAllByEstimateId(id);acceptances.flush();histories.deleteAllByEstimateId(id);histories.flush();lines.deleteAllByEstimateId(id);lines.flush();estimates.delete(e);estimates.flush();}catch(DataIntegrityViolationException x){throw conflict("Estimate cannot be deleted",x);}}

 private void validate(EstimateRequest r){require(machines.existsById(r.machineId()),"Machine",r.machineId());require(technicians.existsById(r.technicianId()),"Technician",r.technicianId());require(users.existsById(r.performedBy()),"User",r.performedBy());if((r.serviceScheduleId()==null)==(r.breakdownId()==null))throw new IllegalArgumentException("Exactly one of serviceScheduleId or breakdownId must be provided");if(r.serviceScheduleId()!=null)require(schedules.existsById(r.serviceScheduleId()),"Service schedule",r.serviceScheduleId());if(r.breakdownId()!=null)require(breakdowns.existsById(r.breakdownId()),"Breakdown",r.breakdownId());if(r.approvedBy()!=null)require(users.existsById(r.approvedBy()),"Approving user",r.approvedBy());for(EstimateLineRequest line:r.lines())validateLine(line);EstimateStatus status=r.status()==null?EstimateStatus.DRAFT:r.status();if(status==EstimateStatus.ACCEPTED){if(r.acceptance()==null)throw new IllegalArgumentException("Acceptance data is required for ACCEPTED estimates");validateAcceptance(r.acceptance());}}
 private void validateLine(EstimateLineRequest l){EstimateLineStatus s=l.lineStatus()==null?(l.partId()!=null?EstimateLineStatus.CATALOG:EstimateLineStatus.PENDING):l.lineStatus();if(s==EstimateLineStatus.CATALOG&&l.partId()==null)throw new IllegalArgumentException("partId is required for CATALOG lines");if(s==EstimateLineStatus.PENDING&&(l.pendingPartName()==null||l.pendingPartName().isBlank()))throw new IllegalArgumentException("pendingPartName is required for PENDING lines");if(l.partId()!=null)require(parts.existsById(l.partId()),"Part",l.partId());if(l.resolvedBy()!=null)require(users.existsById(l.resolvedBy()),"Resolving user",l.resolvedBy());}
 private void validateAcceptance(EstimateAcceptanceData a){if(a.acceptedByType()==EstimateAcceptedByType.PORTAL_CONTACT){if(a.portalAccountId()==null)throw new IllegalArgumentException("portalAccountId is required for PORTAL_CONTACT acceptance");require(portals.existsById(a.portalAccountId()),"Portal account",a.portalAccountId());}else{if(a.recordedByUserId()==null)throw new IllegalArgumentException("recordedByUserId is required for OPERATOR_ON_BEHALF acceptance");require(users.existsById(a.recordedByUserId()),"Recording user",a.recordedByUserId());}}
 private void apply(Estimate e,EstimateRequest r,EstimateStatus status,boolean create,LocalDateTime now){e.setMachineId(r.machineId());e.setServiceScheduleId(r.serviceScheduleId());e.setBreakdownId(r.breakdownId());e.setTechnicianId(r.technicianId());e.setStatus(status);e.setApprovedBy(r.approvedBy());if(r.approvedBy()!=null&&e.getApprovedAt()==null)e.setApprovedAt(now);if(create){e.setCreatedBy(r.performedBy());e.setCreatedAt(now);}}
 private void replaceLines(Long id,List<EstimateLineRequest> data){lines.deleteAllByEstimateId(id);lines.flush();for(EstimateLineRequest r:data){EstimateLine l=new EstimateLine();l.setEstimateId(id);l.setPartId(r.partId());l.setPendingPartName(opt(r.pendingPartName()));l.setQty(r.qty());l.setNote(opt(r.note()));EstimateLineStatus s=r.lineStatus()==null?(r.partId()!=null?EstimateLineStatus.CATALOG:EstimateLineStatus.PENDING):r.lineStatus();l.setLineStatus(s);l.setResolvedBy(r.resolvedBy());l.setResolvedAt(s==EstimateLineStatus.RESOLVED?LocalDateTime.now():null);lines.save(l);}lines.flush();}
 private void addHistory(Long id,EstimateStatus old,EstimateStatus status,Long by,String reason,LocalDateTime at){EstimateStatusHistory h=new EstimateStatusHistory();h.setEstimateId(id);h.setPreviousStatus(old==null?null:old.name());h.setNewStatus(status.name());h.setChangedBy(by);h.setChangedAt(at);h.setReason(opt(reason));histories.saveAndFlush(h);}
 private void syncAcceptance(Long id,EstimateStatus status,EstimateAcceptanceData data,LocalDateTime now){if(status!=EstimateStatus.ACCEPTED){acceptances.deleteAllByEstimateId(id);acceptances.flush();return;}EstimateAcceptance a=acceptances.findByEstimateId(id).orElseGet(EstimateAcceptance::new);a.setEstimateId(id);a.setAcceptedByType(data.acceptedByType());a.setPortalAccountId(data.portalAccountId());a.setRecordedByUserId(data.recordedByUserId());if(a.getAcceptedAt()==null)a.setAcceptedAt(now);a.setReferenceNumber(opt(data.referenceNumber()));a.setNote(opt(data.note()));acceptances.saveAndFlush(a);}
 private Estimate find(Long id){return estimates.findByIdWithDetails(id).orElseThrow(()->new EntityNotFoundException("Estimate "+id+" was not found"));}
 private EstimateResponse response(Estimate e){List<EstimateLineResponse> ls=lines.findAllByEstimateIdOrderByEstimateLineId(e.getEstimateId()).stream().map(l->new EstimateLineResponse(l.getEstimateLineId(),l.getPartId(),l.getPart()==null?null:l.getPart().getPartCode(),l.getPendingPartName(),l.getQty(),l.getNote(),l.getLineStatus(),l.getResolvedBy(),l.getResolvedAt())).toList();List<EstimateStatusHistoryResponse> hs=histories.findAllByEstimateIdOrderByChangedAtAsc(e.getEstimateId()).stream().map(h->new EstimateStatusHistoryResponse(h.getEstimateStatusHistoryId(),h.getPreviousStatus()==null?null:EstimateStatus.valueOf(h.getPreviousStatus()),EstimateStatus.valueOf(h.getNewStatus()),h.getChangedBy(),h.getChangedAt(),h.getReason())).toList();EstimateAcceptanceResponse ar=acceptances.findByEstimateId(e.getEstimateId()).map(a->new EstimateAcceptanceResponse(a.getEstimateAcceptanceId(),a.getAcceptedByType(),a.getPortalAccountId(),a.getRecordedByUserId(),a.getAcceptedAt(),a.getReferenceNumber(),a.getNote())).orElse(null);return new EstimateResponse(e.getEstimateId(),e.getEstimateNumber(),e.getMachineId(),e.getMachine().getMachineReferenceNumber(),e.getServiceScheduleId(),e.getBreakdownId(),e.getTechnicianId(),e.getTechnician().getTechnicianName(),e.getStatus(),e.getApprovedBy(),e.getApprovedAt(),e.getCreatedBy(),e.getCreatedAt(),ls,hs,ar);}
 private void require(boolean ok,String name,Long id){if(!ok)throw new EntityNotFoundException(name+" "+id+" was not found");}private String opt(String s){return s==null||s.isBlank()?null:s.trim();}private IllegalStateException conflict(String m,Exception e){return new IllegalStateException(m+" because a referenced or unique value is invalid",e);}
}
